os: windows

language: shell

env:
  global:
    - VSINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools"

script:
  - cmd.exe /c "\"%VSINSTALLDIR%\\VC\\Auxiliary\\Build\\vcvars64.bat\" && where cl && where nmake && nmake"
